# Generated by Django 5.2.1 on 2025-05-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='norm',
            name='unique_norm_title_and_type',
        ),
        migrations.AlterField(
            model_name='norm',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
