# Generated by Django 5.2.1 on 2025-05-25 12:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_exercise_options_exercise_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
