from ..app.models import Norm, Exercise

norm = Norm.objects.create(title="DKS O - Orientering")
Exercise.objects.create(norm=norm, text="Daglig inspektion")
Exercise.objects.create(norm=norm, text="Tankning af flyet")
Exercise.objects.create(norm=norm, text="Preflight check")
Exercise.objects.create(norm=norm, text="Cockpit check")
Exercise.objects.create(norm=norm, text="Vejret")
Exercise.objects.create(norm=norm, text="Start- og landingsberegning. Hvorfor bruges dette?")
Exercise.objects.create(norm=norm, text="Brændstof (planlagt forbrug)")
Exercise.objects.create(norm=norm, text="Flyets begrænsninger (side- og modvindskomponent)")
Exercise.objects.create(norm=norm, text="Hvad er beregning af max. last vs. MTOM?")
Exercise.objects.create(norm=norm, text="Introduktion til TEM (Threat and Error Management. Risikovurdering")

norm = Norm.objects.create(title="DKS 1 - Kontrol og tilvænningsflyvning")
Exercise.objects.create(norm=norm, text="Daglig inspektion")
Exercise.objects.create(norm=norm, text="Tankning af flyet")
Exercise.objects.create(norm=norm, text="Preflight check")
Exercise.objects.create(norm=norm, text="Cockpit check")
Exercise.objects.create(norm=norm, text="Vejret")
Exercise.objects.create(norm=norm, text="Start- og landingsberegning")
Exercise.objects.create(norm=norm, text="Brændstof (planlagt forbrug)")
Exercise.objects.create(norm=norm, text="Flyets begrænsninger (side- og modvindskomponent)")
Exercise.objects.create(norm=norm, text="Beregning af max. last vs. MTOW")
Exercise.objects.create(norm=norm, text="Introduktion til TEM (Threat and Error Management. Risikovurdering)")
Exercise.objects.create(norm=norm, text="Demonstration af de enkelte ror under flyvning.")
Exercise.objects.create(norm=norm, text="Flyvepladsens placering i forhold til omgivelserne (byer, terræn m.m.)")
Exercise.objects.create(norm=norm, text="Korrekt landingsrunde")
Exercise.objects.create(norm=norm, text="Lokale forhold efter landing (Eks. registrering af starter)")
Exercise.objects.create(norm=norm, text="Fartøjsjournal")
Exercise.objects.create(norm=norm, text="Logbog")
Exercise.objects.create(norm=norm, text="Rengøring af flyet efter flyvning.")